/** ข้อความภาษาไทยสำหรับ UI — แก้ไขที่ไฟล์นี้เป็นหลัก */

export const th = {
  app: {
    name: 'Packing List',
    companyFooter: 'Business & Technology Co., Ltd.',
  },

  nav: {
    home: 'หน้าหลัก',
    documents: 'เอกสาร',
    scan: 'สแกน',
    confirm: 'ปิดงาน',
    print: 'พิมพ์',
    history: 'ประวัติ',
    settings: 'ตั้งค่า',
    logout: 'ออกจากระบบ',
    userFallback: 'ผู้ใช้งาน',
    openMenu: 'เปิดเมนู',
    closeMenu: 'ปิดเมนู',
  },

  auth: {
    loginTitle: 'เข้าสู่ระบบ',
    loginHint: 'กรุณากรอกข้อมูลเพื่อเข้าสู่ระบบ',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    usernamePlaceholder: 'กรุณากรอกชื่อผู้ใช้',
    passwordPlaceholder: 'กรุณากรอกรหัสผ่าน',
    rememberMe: 'จดจำฉัน',
    submit: 'เข้าสู่ระบบ',
    submitting: 'กำลังเข้าสู่ระบบ...',
    failed: 'เข้าสู่ระบบไม่สำเร็จ',
    tagline: 'ระบบบรรจุสินค้า',
    descLine1: 'ตรวจสอบสินค้าและรายการจัดส่ง',
    descLine2: 'อย่างรวดเร็ว',
    orgMissing: 'ยังไม่ได้เลือกบริษัท สาขา หรือคลังสินค้า',
    relogin: 'กรุณาเข้าสู่ระบบใหม่',
    apiSettingsAria: 'ตั้งค่าที่อยู่ API',
  },

  org: {
    tagline: 'เลือกสถานที่ทำงาน',
    descLine1: 'ระบุบริษัท สาขา และคลังสินค้า',
    descLine2: 'ก่อนเริ่มจัดสินค้า',
    title: 'บริษัท สาขา และคลังสินค้า',
    loading: 'กำลังโหลดข้อมูลบริษัท สาขา และคลังสินค้า...',
    ready: 'กรุณาเลือกข้อมูลให้ครบก่อนเริ่มใช้งาน',
    company: 'บริษัท',
    branch: 'สาขา',
    warehouse: 'คลังสินค้า',
    branchPlaceholder: 'เลือกสาขา',
    warehousePlaceholder: 'เลือกคลังสินค้า',
    companyPlaceholder: 'ชื่อบริษัท',
    noBranch: 'ไม่พบสาขา',
    noWarehouse: 'ไม่พบคลังสินค้า',
    requireCompany: 'กรุณากรอกชื่อบริษัท',
    requireBranch: 'กรุณาเลือกสาขา',
    requireWarehouse: 'กรุณาเลือกคลังสินค้า',
    loadFailed: 'โหลดข้อมูลบริษัท สาขา หรือคลังสินค้าไม่สำเร็จ',
    submit: 'ยืนยันและเริ่มใช้งาน',
    submitting: 'กำลังบันทึก...',
    backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
  },

  dashboard: {
    eyebrow: 'ภาพรวม',
    title: 'ภาพรวมงานจัดสินค้า',
    startPacking: '+ เริ่มจัดสินค้า',
    waiting: 'งานรอจัด',
    inProgress: 'งานกำลังจัด',
    done: 'งานเสร็จแล้ว',
    problem: 'งานที่มีปัญหา',
    boxesToday: 'กล่องวันนี้',
    scannedToday: 'สินค้าที่สแกนวันนี้',
    unitItem: 'รายการ',
    unitBox: 'กล่อง',
    unitPiece: 'ชิ้น',
    recentJobs: 'งานล่าสุด',
    viewAll: 'ดูทั้งหมด',
    colDocRef: 'เลขที่เอกสาร',
    colCustomer: 'ลูกค้า',
    colBoxes: 'กล่อง',
    colScanned: 'สแกนแล้ว',
    colPacker: 'ผู้จัด',
    colStatus: 'สถานะ',
    colUpdated: 'อัปเดต',
    empty: 'ยังไม่มีประวัติงาน — เริ่มจากเลือกเอกสาร',
  },

  documents: {
    eyebrow: 'หน้าจอที่ 2 — เลือกเอกสาร',
    title: 'ค้นหาและเลือกเอกสาร',
    fromDate: 'จากวันที่เอกสาร',
    toDate: 'ถึงวันที่เอกสาร',
    datePlaceholder: 'dd/mm/yyyy',
    dateInvalid: 'รูปแบบวันที่ไม่ถูกต้อง (dd/mm/yyyy)',
    fromRef: 'จากเลขที่เอกสาร',
    toRef: 'ถึงเลขที่เอกสาร',
    fromRefPlaceholder: 'เลขที่เริ่มต้น หรือสแกนบาร์โค้ด',
    toRefPlaceholder: 'เลขที่สิ้นสุด หรือสแกนบาร์โค้ด',
    search: 'ค้นหา',
    searching: 'กำลังค้นหา...',
    listTitle: 'รายการเอกสาร',
    startPacking: 'เริ่มจัดสินค้า',
    colRef: 'เลขที่',
    colDate: 'วันที่',
    colCustomer: 'ลูกค้า',
    colStatus: 'สถานะ',
    selectAllAria: 'เลือกหรือยกเลิกเลือกเอกสารทั้งหมด',
    emptyTable: 'ค้นหาเอกสารเพื่อแสดงรายการ',
    notFound: 'ไม่พบเอกสารตามเงื่อนไข',
    searchFailed: 'ค้นหาไม่สำเร็จ',
    selectAtLeastOne: 'กรุณาเลือกอย่างน้อย 1 เอกสาร',
    noLineItems: 'เอกสารที่เลือกไม่มีรายการสินค้า',
    loadFailed: 'โหลดเอกสารไม่สำเร็จ',
    dateRangeInvalid: 'ถึงวันที่ต้องมากกว่าหรือเท่ากับจากวันที่',
    refRangeInvalid: 'ถึงเลขที่ต้องมากกว่าหรือเท่ากับจากเลขที่',
    loadEmpty: 'ไม่พบเลขเอกสารหรือไม่มีข้อมูลตามเงื่อนไขที่เลือก',
  },

  scan: {
    eyebrow: 'หน้าจอที่ 3 — สแกนสินค้า',
    currentBox: 'กล่องปัจจุบัน',
    remainingLines: 'รายการคงเหลือ',
    progressUnit: 'หน่วย',
    pause: 'พักงาน',
    closeJob: 'ปิดงาน',
    tabDoc: 'ข้อมูลเอกสาร',
    tabItems: 'รายการ',
    tabBox: 'กล่อง',
    docInfo: 'ข้อมูลเอกสาร',
    customer: 'ลูกค้า',
    docRef: 'เลขที่',
    date: 'วันที่',
    lines: 'รายการ',
    shippingAddress: 'ที่อยู่จัดส่ง',
    noShippingAddress: 'ไม่พบที่อยู่จัดส่ง',
    multiDocs: (count: number, refs: string) =>
      `${count} เอกสาร (${refs})`,
    remainingTitle: 'รายการสินค้าคงเหลือ',
    colBarcode: 'บาร์โค้ด',
    colSku: 'รหัส',
    colName: 'ชื่อสินค้า',
    colUnit: 'หน่วย',
    colPack: 'บรรจุ',
    colDocQty: 'ตามเอกสาร',
    colScanned: 'สแกนแล้ว',
    colRemaining: 'คงเหลือ',
    colStatus: 'สถานะ',
    colDocRef: 'เลขที่เอกสาร',
    boxTitle: 'กล่อง',
    colQty: 'จำนวน',
    colWeight: 'น้ำหนัก',
    remove: 'ลบ',
    emptyBox: 'ยังไม่มีสินค้าในกล่องนี้',
    closeBox: 'ปิดกล่อง',
    nextCustomer: 'ลูกค้าถัดไป',
    scanTitle: 'สแกนบาร์โค้ด',
    scanPlaceholder: 'สแกนบาร์โค้ด หรือ 3*8859126000515',
    qtyLabel: 'จำนวน',
    weightLabel: 'น้ำหนัก (กรัม)',
    weightPlaceholder: '0',
    undo: 'ยกเลิก',
    save: 'บันทึก',
    keyboardOpen: 'เปิดแป้นพิมพ์',
    keyboardClose: 'ปิดแป้นพิมพ์',
    cameraScan: 'สแกนด้วยกล้อง',
    tabsAria: 'ข้อมูลงานสแกน',
    genericError: 'เกิดข้อผิดพลาด',
    scanSuccess: (boxNo: number) => `สแกนสำเร็จ — กล่อง ${boxNo}`,
    removedFromBox: 'ลบรายการออกจากกล่องแล้ว',
    undoSuccess: 'ยกเลิกรายการสแกนล่าสุด',
    closeBoxSuccess: (closed: number, next: number) =>
      `ปิดกล่อง ${closed} แล้ว — กล่องถัดไป ${next}`,
    lastCustomerDone: (label: string) =>
      `ตรวจสอบลูกค้า ${label} ครบแล้ว — ไม่มีลูกค้าถัดไป`,
    nextCustomerSuccess: (code: string, name: string | undefined, ref: string) =>
      `ไปลูกค้าถัดไป ${code}${name ? ` — ${name}` : ''} (${ref})`,
  },

  confirm: {
    eyebrow: 'หน้าจอที่ 4 — ตรวจสอบก่อนปิดงาน',
    title: 'สรุปก่อนปิดงาน',
    docQty: 'ตามเอกสาร',
    scannedQty: 'จัดแล้ว',
    shortQty: 'ขาด',
    overQty: 'เกิน',
    boxCount: 'จำนวนกล่อง',
    anomalies: 'รายการผิดปกติ',
    packer: 'ผู้จัดสินค้า',
    checker: 'ผู้ตรวจสอบ',
    notes: 'หมายเหตุ',
    partialCheckbox: 'ยืนยันปิดงานแบบสินค้าไม่ครบ (ผู้มีสิทธิ์)',
    backToScan: 'กลับไปแก้ไข',
    pause: 'บันทึกพักงาน',
    submit: 'ยืนยันปิดงาน',
    partialAlert:
      'ยังมีรายการผิดปกติ — ติ๊กยืนยันปิดงานแบบไม่ครบ (ผู้มีสิทธิ์) หรือกลับไปแก้ไข',
    anomalyShort: (qty: number) => `จัดสินค้าขาด ${qty} หน่วย`,
    anomalyOver: (qty: number) => `สินค้าเกิน ${qty} หน่วย`,
    anomalyNotBoxed: 'มีสินค้าที่สแกนแล้วแต่ยังไม่ได้ใส่กล่อง',
    anomalyBoxNotClosed: 'มีรายการครบแล้วแต่ยังไม่ได้ปิดกล่อง',
  },

  print: {
    eyebrow: 'หน้าจอที่ 5 — พิมพ์เอกสาร',
    title: 'พิมพ์ใบปะกล่องและรายการบรรจุ',
    layoutHint: 'ใบปะกล่อง A4 2 ใบ (บน-ล่าง)',
    selectBoxes: 'เลือกกล่อง',
    allBoxes: 'ทุกกล่อง',
    clear: 'ล้าง',
    boxClosed: 'ปิดแล้ว',
    boxHasItems: 'มีสินค้า',
    pieces: 'ชิ้น',
    noPrintableBoxes: 'ยังไม่มีกล่องที่พิมพ์ได้ — ปิดกล่องหรือสแกนสินค้าก่อน',
    labelTemplate: 'แม่แบบใบปะกล่อง',
    packingTemplate: 'แม่แบบรายการบรรจุ',
    printer: 'เครื่องพิมพ์สติ๊กเกอร์ A4',
    printerPlaceholder: 'ชื่อเครื่องพิมพ์สติ๊กเกอร์ A4',
    copies: 'จำนวนสำเนา (ใบปะกล่อง)',
    previewLabel: 'ตัวอย่างใบปะกล่อง',
    previewPacking: 'ตัวอย่างรายการบรรจุ',
    printLabel: 'พิมพ์ใบปะกล่อง',
    printPacking: 'พิมพ์รายการบรรจุ',
    downloadPdf: 'ดาวน์โหลด PDF',
    reprintLatest: 'พิมพ์ซ้ำล่าสุด',
    previewTitleLabel: 'ตัวอย่างใบปะกล่อง',
    previewTitlePacking: 'ตัวอย่างรายการบรรจุ',
    page: 'หน้า',
    previewFrameTitle: 'ตัวอย่างเอกสารพิมพ์',
    tabPreview: 'ตัวอย่าง',
    tabHistory: 'ประวัติการพิมพ์',
    tabsAria: 'แท็บตัวอย่างและประวัติการพิมพ์',
    historyEmpty: 'ยังไม่มีประวัติการพิมพ์',
    previewSelectBoxes: 'เลือกกล่องเพื่อดูตัวอย่างก่อนพิมพ์',
    historyLabel: 'ใบปะกล่อง',
    historyPacking: 'รายการบรรจุ',
    selectBoxRequired: 'กรุณาเลือกกล่องที่ต้องการพิมพ์',
    noLabelData: 'ไม่พบข้อมูลใบปะกล่องสำหรับกล่องที่เลือก',
    noPackingData: 'ยังไม่มีรายการสำหรับรายการบรรจุ — เลือกกล่องที่มีสินค้า',
    noPdf: 'ยังไม่มีเอกสารสำหรับบันทึก PDF',
    pdfHint:
      'เปิดหน้าพิมพ์แล้ว — เลือกเครื่องพิมพ์เป็น “บันทึกเป็น PDF” หรือ “Microsoft Print to PDF”',
    previewLabelNotice: 'แสดงตัวอย่างใบปะกล่อง A4 2 ใบ (บน-ล่าง)',
    previewPackingNotice: 'แสดงตัวอย่างรายการบรรจุ',
    printedAll: (count: number) =>
      `พิมพ์ทุกกล่อง (${count}) บนใบปะกล่อง A4 2 ใบ (บน-ล่าง)`,
    printedSome: (count: number) =>
      `พิมพ์ ${count} กล่อง บนใบปะกล่อง A4 2 ใบ (บน-ล่าง)`,
    packingPrinted: 'พิมพ์รายการบรรจุแล้ว',
    reprint: (title: string) => `พิมพ์ซ้ำ: ${title}`,
    labelDocTitle: (ref: string) => `ใบปะกล่อง ${ref}`,
    packingDocTitle: (ref: string) => `รายการบรรจุ ${ref}`,
    historyBoxes: (boxes: string, copies: number) =>
      `กล่อง ${boxes} · สำเนา ${copies}`,
    historyBoxesAll: (boxes: string) => `กล่อง ${boxes} · ทั้งหมด`,
  },

  history: {
    eyebrow: 'หน้าจอที่ 6 — ประวัติการทำงาน',
    title: 'ประวัติงานจัดสินค้า',
    search: 'ค้นหาเอกสารหรือผู้ใช้',
    status: 'สถานะ',
    all: 'ทั้งหมด',
    colDoc: 'เอกสาร',
    colStarted: 'เริ่ม',
    colClosed: 'ปิด',
    colPacker: 'ผู้จัด',
    colChecker: 'ผู้ตรวจ',
    colBoxes: 'กล่อง',
    colStatus: 'สถานะ',
    empty: 'ไม่พบประวัติ',
  },

  settings: {
    eyebrow: 'หน้าจอที่ 7 — ตั้งค่าระบบ',
    title: 'ตั้งค่า Packing List',
    save: 'บันทึก',
    saved: 'บันทึกแม่แบบและเครื่องพิมพ์แล้ว',
    erpTitle: 'การเชื่อมต่อ Bplus ERP',
    erpUrlLabel: 'ที่อยู่ API ปัจจุบัน:',
    erpConfigure: 'ตั้งค่า API',
    soundTitle: 'เสียงแจ้งเตือน',
    soundDesc: 'เล่นเสียงเมื่อสแกนสำเร็จหรือผิดพลาด',
    soundOn: 'เปิดเสียง',
    soundToggleAria: 'เปิดหรือปิดเสียงแจ้งเตือน',
    printTitle: 'แม่แบบและเครื่องพิมพ์',
    printOrgHint: 'ผูกตามบริษัทและสาขาที่เลือกเข้าใช้งาน',
    labelTemplate: 'แม่แบบใบปะกล่อง',
    packingTemplate: 'แม่แบบรายการบรรจุ',
    labelPrinter: 'เครื่องพิมพ์ใบปะกล่อง',
    a4Printer: 'เครื่องพิมพ์ A4',
    printerExampleZebra: 'เช่น Zebra ZD220',
    printerExampleHp: 'เช่น HP LaserJet',
  },

  erpSettings: {
    title: 'ตั้งค่าที่อยู่ API',
    hint:
      'ที่อยู่ Bplus ERP Web Service — เปิดโหมด HTTP สำหรับเชื่อมต่อใน LAN โดยไม่ใช้ SSL',
    fieldLabel: 'ที่อยู่ API',
    test: 'ทดสอบการเชื่อมต่อ',
    testing: 'กำลังทดสอบ...',
    reset: 'ค่าเริ่มต้น',
    close: 'ปิด',
    save: 'บันทึก',
    saved: 'บันทึกสำเร็จ',
    resetDone: 'รีเซ็ตเป็นค่าเริ่มต้นแล้ว',
    activeUrl: 'ที่อยู่ที่ใช้งาน (localStorage)',
    envOptional: 'ดูค่าสำหรับใส่ใน .env (ไม่บังคับ)',
    testOk: 'เชื่อมต่อ ERP ได้ (โปรพิเตทหรือพร็อกซีทำงาน)',
    testFailed: 'ทดสอบการเชื่อมต่อไม่สำเร็จ',
    httpMode: 'ใช้ HTTP (ไม่ใช้ SSL)',
    httpModeHint:
      'เปิดเพื่อเชื่อมต่อผ่าน http:// แทน https:// เหมาะกับ ERP ในเครือข่ายภายใน',
    effectiveUrl: 'ที่อยู่ที่ใช้เชื่อมต่อจริง',
  },

  erpErrors: {
    mixedContent:
      'เชื่อม ERP ไม่ได้ — หน้าเว็บเปิดผ่าน HTTPS แต่ ERP เป็น HTTP (เบราว์เซอร์บล็อก Mixed Content) ให้ตั้งที่อยู่ API เป็น /erp ผ่าน reverse proxy หรือเปิดเว็บด้วย HTTP',
    cors:
      'เชื่อม ERP ไม่ได้ — เรียก ERP ข้าม origin (CORS) แนะนำตั้งที่อยู่ API เป็น /erp แล้วเปิด reverse proxy ที่ IIS หรือ nginx',
    generic: (detail: string) => `เชื่อม ERP ไม่ได้ — ${detail}`,
    fallback:
      'เชื่อม ERP ไม่ได้ — ตรวจที่อยู่ API และการเชื่อมต่อเครือข่าย',
    responseCode: (code: string) => `ERP ตอบกลับรหัส ${code}`,
    emptyResponse: 'ERP ตอบกลับว่าง',
    sslHostname:
      'เชื่อม ERP ไม่ได้ — ใบรับรอง SSL ไม่ตรงกับ IP (Hostname not verified) กรุณา build แอปใหม่หลังอัปเดต หรือใช้ชื่อเซิร์ฟเวอร์ที่ตรงกับใบรับรองแทน IP',
  },

  sessionErrors: {
    closed: 'รายการสแกนถูกปิดแล้ว',
    barcodeNotFound: (barcode: string) =>
      `ไม่พบบาร์โค้ด ${barcode} ในรายการนี้ หรือสแกนครบแล้ว`,
    wrongCustomer: (scanned: string, active: string) =>
      `สินค้านี้อยู่ในเอกสารของลูกค้า ${scanned} ไม่ใช่ลูกค้าที่กำลังสแกน (${active})`,
    wrongDocument: (scannedRef: string, activeRef: string) =>
      `สินค้านี้อยู่ในเอกสาร ${scannedRef} ไม่ใช่เอกสารที่กำลังสแกน (${activeRef})`,
    qtyExceeds: (requested: number, available: number) =>
      `จำนวนที่ขอ ${requested} เกินจำนวนคงเหลือ ${available}`,
    emptyBox: (boxNo: number) => `กล่อง ${boxNo} ยังไม่มีสินค้าที่สแกน`,
    closeBoxPartyIncomplete:
      'ไม่สามารถปิดกล่องได้ — ต้องสแกนรายการสินค้าของลูกค้ารายนี้ให้ครบก่อน',
    closeBoxPartial:
      'ไม่สามารถปิดกล่องได้ — ยังมีสินค้าที่สแกนไม่ครบ',
    noUndo: 'ไม่มีรายการสแกนล่าสุดให้ยกเลิก',
    undoTargetMissing: 'ไม่พบรายการที่จะยกเลิก',
    boxItemMissing: 'ไม่พบรายการในกล่อง',
    noPartyDocs: 'ไม่พบเอกสารของลูกค้าที่กำลังจัด',
    noActiveDoc: 'ยังไม่ได้เลือกเอกสารที่กำลังสแกน',
    noDocuments: 'ไม่มีเอกสารในรายการ',
    activeDocMissing: 'ไม่พบเอกสารที่กำลังสแกนในรายการ',
    scanIncomplete:
      'ยังสแกนสินค้าไม่ครบ — ต้องสแกนให้ครบก่อนไปลูกค้าถัดไป',
    boxesOpen:
      'ยังมีกล่องที่ยังไม่ได้ปิด — ต้องปิดกล่องให้ครบก่อนไปลูกค้าถัดไป',
    docItemsMissing: (ref: string | number) =>
      `ไม่พบรายการสินค้าในเอกสาร ${ref}`,
    partyDocsMissing: (code: string) =>
      `ไม่พบเอกสารของลูกค้า ${code}`,
    unknownParty: 'ไม่ระบุ',
  },

  scanInput: {
    dialogTitle: '\u0e40\u0e25\u0e37\u0e2d\u0e01\u0e27\u0e34\u0e18\u0e35\u0e2a\u0e41\u0e01\u0e19\u0e1a\u0e32\u0e23\u0e42\u0e04\u0e49\u0e14',
    dialogHint:
      '\u0e40\u0e25\u0e37\u0e2d\u0e01\u0e04\u0e23\u0e31\u0e49\u0e07\u0e41\u0e23\u0e01 \u0e23\u0e30\u0e1a\u0e1a\u0e08\u0e30\u0e08\u0e33\u0e04\u0e48\u0e32\u0e44\u0e27\u0e49 \u0e41\u0e01\u0e49\u0e44\u0e02\u0e44\u0e14\u0e49\u0e17\u0e35\u0e48\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32',
    scannerTitle: '\u0e15\u0e31\u0e27\u0e2d\u0e48\u0e32\u0e19 Barcode (Scanner)',
    scannerDesc:
      '\u0e43\u0e0a\u0e49\u0e01\u0e31\u0e1a\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e2d\u0e48\u0e32\u0e19 USB/Bluetooth \u0e2b\u0e23\u0e37\u0e2d PDA',
    cameraTitle: '\u0e01\u0e25\u0e49\u0e2d\u0e07\u0e21\u0e37\u0e2d\u0e16\u0e37\u0e2d/\u0e41\u0e17\u0e47\u0e1a\u0e40\u0e25\u0e47\u0e15',
    cameraDesc:
      '\u0e2a\u0e41\u0e01\u0e19\u0e14\u0e49\u0e27\u0e22\u0e01\u0e25\u0e49\u0e2d\u0e07\u0e2b\u0e19\u0e49\u0e32\u0e08\u0e2d (\u0e41\u0e19\u0e30\u0e19\u0e33 HTTPS \u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e01\u0e25\u0e49\u0e2d\u0e07\u0e2a\u0e14)',
    keyboardTitle: '\u0e1e\u0e34\u0e21\u0e1e\u0e4c\u0e14\u0e49\u0e27\u0e22\u0e21\u0e37\u0e2d',
    keyboardDesc:
      '\u0e40\u0e1b\u0e34\u0e14\u0e41\u0e1b\u0e49\u0e19\u0e1e\u0e34\u0e21\u0e1e\u0e4c\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e01\u0e23\u0e2d\u0e01\u0e23\u0e2b\u0e31\u0e08\u0e14\u0e49\u0e27\u0e22\u0e21\u0e37\u0e2d',
    confirm: '\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19',
    hintScanner:
      '\u0e42\u0e2b\u0e21\u0e14: \u0e15\u0e31\u0e27\u0e2d\u0e48\u0e32\u0e19 Barcode \u2014 \u0e42\u0e1f\u0e01\u0e31\u0e2a\u0e17\u0e35\u0e48\u0e0a\u0e48\u0e2d\u0e07\u0e41\u0e25\u0e49\u0e27\u0e2a\u0e41\u0e01\u0e19',
    hintCamera:
      '\u0e42\u0e2b\u0e21\u0e14: \u0e01\u0e25\u0e49\u0e2d\u0e07 \u2014 \u0e01\u0e14\u0e1b\u0e38\u0e48\u0e21\u0e01\u0e25\u0e49\u0e2d\u0e07\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e2a\u0e41\u0e01\u0e19',
    hintKeyboard:
      '\u0e42\u0e2b\u0e21\u0e14: \u0e41\u0e1b\u0e49\u0e19\u0e1e\u0e34\u0e21\u0e1e\u0e4c \u2014 \u0e1e\u0e34\u0e21\u0e1e\u0e4c\u0e23\u0e2b\u0e31\u0e2a\u0e14\u0e49\u0e27\u0e22\u0e21\u0e37\u0e2d',
    settingsLabel: '\u0e27\u0e34\u0e18\u0e35\u0e2a\u0e41\u0e01\u0e19\u0e1a\u0e32\u0e23\u0e42\u0e04\u0e49\u0e14',
  },

  camera: {
    inUse:
      'เปิดกล้องไม่ได้ — ตรวจว่าไม่มีแอปอื่นใช้กล้องอยู่ และอนุญาตสิทธิ์กล้องในเบราว์เซอร์',
    denied: 'ไม่ได้รับสิทธิ์ใช้กล้อง — กดอนุญาตกล้องในเบราว์เซอร์',
    notFound: 'ไม่พบกล้อง — ใช้ถ่ายรูปบาร์โค้ดแทน',
    httpsRequired: 'เบราว์เซอร์ต้องเปิดผ่าน HTTPS จึงจะใช้กล้องสดได้',
    fallback: (message: string) => `${message} — ลองใช้ถ่ายรูปบาร์โค้ดแทน`,
    liveUnavailable:
      'เปิดกล้องสดไม่ได้ — ใช้ถ่ายรูปบาร์โค้ดแทน',
    readFailed: 'อ่านบาร์โค้ดจากรูปไม่ได้ — ลองถ่ายใหม่ให้ชัดขึ้น',
    httpPhotoMode:
      'เข้าผ่าน HTTP — เบราว์เซอร์ไม่อนุญาตกล้องสด ให้ถ่ายรูปบาร์โค้ด',
    tempUnavailable:
      'กล้องสดใช้ไม่ได้ชั่วคราว — ถ่ายรูปบาร์โค้ดแทน',
    reading: 'กำลังอ่านบาร์โค้ด...',
    capturePhoto: 'ถ่ายรูปบาร์โค้ด',
    liveHint: 'ชี้กล้องไปที่บาร์โค้ด — ระบบจะกรอกให้อัตโนมัติ',
    switchToPhoto: 'ใช้ถ่ายรูปแทน',
    switchCamera: 'สลับกล้อง',
  },

  workflow: {
    waiting: 'รอจัดสินค้า',
    packing: 'กำลังจัดสินค้า',
    paused: 'พักงาน',
    done: 'เสร็จสิ้น',
    printed: 'พิมพ์เอกสารแล้ว',
    closedLegacy: 'ปิดงานแล้ว',
  },

  printTemplates: {
    labelDefault: 'มาตรฐาน (A4 2 ใบ · บน-ล่าง)',
    packingDefault: 'มาตรฐาน (Letter · 1 กล่องต่อ 1 แบบฟอร์ม)',
    packingByBox: 'แยกตารางตามกล่อง (Letter · 1 กล่องต่อ 1 แบบฟอร์ม)',
  },

  jobActions: {
    start: 'เริ่มจัดสินค้า',
    update: 'อัปเดตงาน',
    pause: 'พักงาน',
    close: 'ปิดงาน',
    closePartial: 'ปิดงาน (ไม่ครบ)',
    printLabel: 'พิมพ์ใบปะกล่อง',
    printPacking: 'พิมพ์รายการบรรจุ',
    reprint: 'พิมพ์ซ้ำ',
  },
} as const;
